#if !canImport(ObjectiveC)
import XCTest

extension UnknownFileTypeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UnknownFileTypeTests = [
        ("testUnknownFileTypesShouldThrowAnError", testUnknownFileTypesShouldThrowAnError),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(UnknownFileTypeTests.__allTests__UnknownFileTypeTests),
    ]
}
#endif
