#if !canImport(ObjectiveC)
import XCTest

extension ApkParsingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ApkParsingTests = [
        ("testBasicMetadata", testBasicMetadata),
    ]
}

extension IpaParsingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IpaParsingTests = [
        ("testBasicMetadata", testBasicMetadata),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ApkParsingTests.__allTests__ApkParsingTests),
        testCase(IpaParsingTests.__allTests__IpaParsingTests),
    ]
}
#endif
